### ISSUE TITLE
Option to extract zip missing

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/file-roller-contract#3]
## What Happened

![Screenshot from 2021-08-05 01 45 32](https://user-images.githubusercontent.com/13716824/128278029-25f5e032-4b16-4389-86c9-436365e9948b.png)

## Expected Behavior
An option to extract to a folder should appear, as in Hera

## Steps to Reproduce

1. Make a .zip
2. Right click it

## Platform Information
Fresh install of Odin RC2

**Comment by danirabbit** [comment]
File roller contract is now built into stable, so this should be resolved! It doesn't look like the package is automatically pulled in on update, so you'll need to manually install `io.elementary.contractor.file-roller`

However, I can confirm that the package is recommends in the desktop metapackage, so this should be fixed in the next RC

**Comment by ChildishGiant** [comment]
Confirmed fixed on RC 3 for me too! Nice work 😄️
